{% set name = "pymt_prms_surface" %}
{% set version = "0.2.1" %}
{% set build_number = "2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/pymt-lab/{{ name }}
  git_rev: v{{ version }}

build:
  number: {{ build_number }}
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - {{ compiler('fortran') }}
    - libnetcdf
    - netcdf-fortran
  host:
    - python
    - cython
    - numpy >=1.14
    - bmi-fortran
    - prms
    - prms_surface
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - bmi-fortran
    - prms
    - prms_surface

test:
  imports:
    - pymt_prms_surface

about:
  summary: Python package that wraps the PRMS Surface BMI.
  home: https://github.com/pymt-lab/pymt_prms_surface
  license: MIT license
  license_file: LICENSE
  dev_url: https://github.com/pymt-lab/pymt_prms_surface
